{
    "name": "TransUM",
    "summary": "Transitar alunos entre planos de estudos facilmente!",
    "depends": ["base"],
    "data": [
            "security/groups.xml",
            "security/ir.model.access.csv",
            "views/administrador_view.xml",
            "views/aluno_view.xml", 
            "views/curso_view.xml",           
            "views/direcao_curso_view.xml",   
            "views/docente_view.xml",                
            "views/plano_curso_view.xml", 
            "views/plano_estudos_uc_view.xml", 
            "views/plano_estudos_view.xml", 
            "views/plano_transicao_uc_view.xml", 
            "views/plano_transicao_view.xml", 
            "views/proposta_novo_plano_view.xml",
            "views/uc_view.xml",
            "views/transum_menu.xml",           
    ],
    'application': True,
}
